---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: glpi-mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glpi-mariadb
  strategy:
    type: Recreate
  template:
    spec:

      containers:

        - name: mariadb
          image: mariadb:10.5
          ports:
            - containerPort: 3306
              name: mariadb
            - containerPort: 33060
              name: mariadb-x
          envFrom:
            - secretRef:
                name: glpi
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mariadb-data

      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: mariadb-data
