apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  selector:
    app: glpi-mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: mariadb
      name: mariadb
    - protocol: TCP
      port: 33060
      targetPort: mariadb-x
      name: mariadb-x
---
apiVersion: v1
kind: Service
metadata:
  name: glpi-fpm
spec:
  selector:
    app: glpi
  ports:
    - protocol: TCP
      port: 9000
      targetPort: glpi-fpm
---
apiVersion: v1
kind: Service
metadata:
  name: glpi
spec:
  selector:
    app: glpi-nginx
  ports:
    - protocol: TCP
      port: 8080
      targetPort: nginx
